export const categories = [
  "Shoes",
  "Accessories",
  "T-Shirts",
  "Bags & Tote",
  "Polo Shirts",
  "Jackets & Coats",
  "Jeans",
  "Trousers & Pants",
  "Skirts",
  "Dresses",
  "Suits & Blazers",
  "Footwear",
  "Men's Clothing",
  "Women's Clothing",
  "Kids' Clothing",
  "Unisex",
  "Hoodies",
  "Plus Size",
  "Other",
];
